### PR TITLE
Webkit2 4.0 port

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by chimosky** [comment]
@quozl kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed to efdc0ae.  Tested on Ubuntu 17.10.  Fixes https://github.com/godiard/help-activity/issues/33.

Did this;
* rebase to master, as master has moved quite a bit since you branched from it for this port; the rebase was clean and simple, and the command was `git pull --rebase origin master`,
* reworked the zoom buttons, as they gave a log error when used; please review d53abd5,
* avoided use of WebKit 3.0 API name; please review a532b13,
* checked no new flake8 warnings or errors,
* tested again,
* captured screenshots of master vs this branch, for use in new issue, https://github.com/godiard/help-activity/issues/100,
* force pushed.

After your review, plan to rewrite the history on this branch before merging.  New issue won't block merge.

**Comment by quozl** [comment]
Further testing exposes a latent bug; images are not shown.  To reproduce, build the content, make a bundle, install it, start the activity, click on Home link, result is;

screenshot_ubb_2018-07-26_17 26 30

Now the `_images` directory is missing by design, as it is omitted from the bundle by `setup.py`.  It works with WebKit 3.0 API browser because it accepts `` and is willing to look in the `images` directory, but the WebKit2 4.0 API browser insists on the correct file name.  

ZIP format can handle symlinks, but they aren't created in the build process as far as I can see, and the exclusion in `setup.py` removes them.  Any ideas?

**Comment by chimosky** [comment]
> Further testing exposes a latent bug; images are not shown. To reproduce, build the content, make a bundle, install it, start the activity, click on Home link, result is;

I can't reproduce, images are showing in mine.
](https://postimg.cc/image/oone10hrl/)

> captured screenshots of master vs this branch, for use in new issue, #100,

Scrollbar rendering works fine in mine too.

I don't know why mine is `Sugar 0.106 documentation` after building the content and making a bundle.

**Comment by chimosky** [comment]
@quozl, i tested and i don't get the same behaviour.

**Comment by quozl** [comment]
Interesting, thanks.  Please show me the contents of the bundle you built.

**Comment by chimosky** [comment]
@quozl the image is [here](http://people.sugarlabs.org/ibiamchihurumnaya/)

**Comment by quozl** [comment]
Thanks.  In your bundle;
* the `images/` directory contains the images (not `_images/`),
* the `html/home_view.html` file has an `img` tag that references `_images/` (not `images/`).

This is technically invalid; the browser should try to open a directory `_images` but somehow opens a directory `images`.

So why is it working for you and not for me?  Please suggest actions to diagnose.

**Comment by chimosky** [comment]
@quozl can you test again with sugar v0.116, I just tested and I don't face any issue you mentioned above.

**Comment by quozl** [comment]
Sure.  Retested the _dist_xo_ bundle on Ubuntu 17.10 with Sugar 0.116.

* [ ] the images in the Home View are not shown, as before in July 2018,
* [ ] both your bundle and mine have an _img_ tag with _src_ set to "_images/Home_icon.png" yet there is no directory named "_images" in the directory "html", though there is a directory "images" next to the directory "html".

Neither of these are created by Sugar, so the version of Sugar is unsurprisingly ineffective.

**Comment by quozl** [comment]
Never mind, my mistake.  I had not tested before your changes.  Having done that, the same problem occurs, so there's no reason not to merge.

**Comment by quozl** [comment]
Rebased.

**Pull request merged**
