### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by chimosky**
Add commit from sugar fork.

@quozl kindly review.

### CODE REVIEW

**Comment by Yasshcodes** [comment]
Hey @chimosky , could you please help me set up this project on my local machine?

**Comment by quozl** [comment]
Why do you need the project set up?  What do you want to do with the project?

**Comment by Yasshcodes** [comment]
I was looking to resolve if there are any bugs in this project.

**Comment by quozl** [comment]
Oh, good.

**Pull request merged**
