### PR TITLE
Migrate documentation from wiki.sugarlabs.org

### PR DESCRIPTION
**Pull request by rdrsadhu**
This Pull Request migrates documentation from

1. https://wiki.sugarlabs.org/go/Activities/AEIOU
2. https://wiki.sugarlabs.org/go/Activities/I_can_read
3. https://wiki.sugarlabs.org/go/Activities/IKnowMyABCs
4. https://wiki.sugarlabs.org/go/Activities/LetterMatch

These 4 pages are migrated together because, each is linked to the other 3.

Each commit migrates one page.

every commit:
* moves the page (+ all associated files-images/audio)
* updates links
* adds new page to [source/index.rst](https://github.com/godiard/help-activity/blob/master/source/index.rst)
* adds new page to [helplink.json](https://github.com/godiard/help-activity/blob/master/helplink.json)

Steps to perform after this Pull Request gets merged:
- [ ] Deprecate wiki-pages 1,2,3,4
Note:
* [Activities/Icanread](https://wiki.sugarlabs.org/index.php?title=Activities/Icanread&redirect=no) redirects to 2
* [Activities/I_Know_My_ABCs](https://wiki.sugarlabs.org/index.php?title=Activities/I_Know_My_ABCs&redirect=no) redirects to 3
- [ ] Add README to the source repositories ([1](https://github.com/sugarlabs/AEIOU), [2](https://github.com/sugarlabs/i-can-read-activity), [3](https://github.com/sugarlabs/iknowmyabcs), [4](https://github.com/sugarlabs/lettermatch)) which points to this user documentation as available in [browse](https://github.com/sugarlabs/browse-activity), [speak](https://github.com/sugarlabs/speak) and [memorize](https://github.com/sugarlabs/memorize-activity)

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.

**Comment by quozl** [comment]
It is because we have two competing pull-requests that I'm joyfully delaying merge until I see consensus.  Both pull-requests have merit.  https://github.com/godiard/help-activity/pull/41 vs https://github.com/sugarlabs/i-can-read-activity/pull/6.

**Comment by quozl** [comment]
Should this be rebased?

**Comment by rdrsadhu** [comment]
merge conflicts resolved.

**Comment by quozl** [comment]
Thanks.

**Pull request merged**
