### PR TITLE
Migrate Ruler documentation from Wiki

### PR DESCRIPTION
**Pull request by vipulgupta2048**
This PR migrates wiki-pages of Ruler Activity from https://wiki.sugarlabs.org/go/Activities/ruler [1]
to the help-activity, for the user to access easily from the device (using the shortcut  `alt + shift + h`)

**To-do** 
- [ ]  When PR is merged; Depreciate [1] and images associated with it, link the wiki-page back to the repository. 
- [ ]  Add a README.md to [sugarlabs/ruler](www.gtihub.com/sugarlabs/ruler) pointing back to user-documentation.

**Status - Incomplete**

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed to 69b9796.

* [ ] link in commit message does not work; should be Ruler not ruler,
* [ ] content refers to bugs.sugarlabs.org instead of Ruler issues on GitHub,
* [ ] unwilling to merge documentation for an activity that does not even work, as this will cause learners to try to download and use the activity once the help.sugarlabs.org site or Help Activity is updated, see https://github.com/sugarlabs/ruler/issues/4, https://github.com/sugarlabs/ruler/issues/3, and https://github.com/sugarlabs/ruler/issues/6.

**Comment by vipulgupta2048** [comment]
I honestly didn't take a look at the issues, after the script was done. I understand your unwillingness and accept the decision made. Reading the documentation for a program that doesn't even work is just a waste of time and energy. I will take care of the same next time onwards (Noted in my checklist) 
Till then, I think we can keep this PR open, till the issues for Ruler activity has been resolved.

**Comment by vipulgupta2048** [comment]
- Comment message amended. 
- Reporting bugs now refer to making new issues and viewing all issues open on Ruler's GitHub repository.
Thanks for the review.

**Comment by quozl** [comment]
Reviewed again.  Continuing to delay merge until work is done to fix Ruler activity.

**Comment by quozl** [comment]
Cherry-picked as 976f3ff3b970ca3afd59b2d7dabc6293fb6b57c4.

**Pull request closed without merging**
