### PR TITLE
Migrate documentation from wiki.sugarlabs.org

### PR DESCRIPTION
**Pull request by rdrsadhu**
This Pull Request migrates documentation from

1. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Challenges
2. https://wiki.sugarlabs.org/go/Activities/Turtle_Confusion

These 2 pages are migrated together because, each links to the other.

Each commit migrates one page.

every commit:
* moves the page(+ all associated images)
* updates links

Steps to perform after this Pull Request gets merged:
- [ ] Deprecate wiki-pages 1,2
Note: [Activities/TurtleArt/Challenges](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Challenges&redirect=no) redirects to 1 

- [ ] Add README to [activity-turtle-confusion](https://github.com/sugarlabs/activity-turtle-confusion) which points to this user documentation.

### CODE REVIEW

**Comment by rdrsadhu** [comment]
These content should be moved to the help-activity because;
1. it brings in a consistent way of documenting things across the organization, as already available in [[a]browse](https://github.com/sugarlabs/browse-activity), [[b]speak](https://github.com/sugarlabs/speak) and [[c]memorize](https://github.com/sugarlabs/memorize-activity) where,
* the content is at help-activity ([[a]](https://github.com/godiard/help-activity/blob/master/source/browse.rst), [[b]](https://github.com/godiard/help-activity/blob/master/source/speak.rst), [[c]](https://github.com/godiard/help-activity/blob/master/source/memorize.rst))
* and the individual READMEs ([[a]](https://github.com/sugarlabs/browse-activity/blob/master/README.md), [[b]](https://github.com/sugarlabs/speak/blob/master/README.md), [[c]](https://github.com/sugarlabs/memorize-activity/blob/master/README.md)) points to [help.sugarlabs.org](https://help.sugarlabs.org/en/) (check "How to use')

2. the information all these pages contain, is more inclined towards a sugar-user (students/teachers/learner) than a sugar-developer,

3. storing these documentations in the help-activity makes it available when an user searches for contextual help(by pressing <kbd>alt</kbd> + <kbd>shift</kbd> + <kbd>h</kbd>) from within another activity.

**Comment by quozl** [comment]
@rdrsadhu, thanks for that; two comments;
* the metadata files have not changed, so I'm not sure how a sugar-user could read the new content,
* the files added to `images/` could be given a name that identifies them with the activity.

@walterbender, as you're one of the Turtle Art developers, might you also review?

**Comment by rdrsadhu** [comment]
Thanks @quozl,

> the metadata files have not changed

Updated.

> the files added to images/ could be given a name that identifies them with the activity

the migration process fetches images/files from the wiki as is(ie without changing size/name/anything-else),
I fear, renaming the images would make the process complex and bring in redundant manual efforts.
If not a very high priority thing, I  prefer leaving them unchanged.

**Comment by quozl** [comment]
Thanks.  Merged.  a28ba5a15d33be2e9b462e1f33a8ca6c92207fda and 79278e8f8d7ff768805bc5bf030f0a03963f5da9. What I fixed was;

* your changes to `source/index.rst` and `helplink.json` placed Turtle Confusion before Turtle Art; not correct lexical order.
* a link to "here".

**Pull request closed without merging**
