### PR TITLE
Migrate Turtle-Art Tutorial documentation from wiki

### PR DESCRIPTION
**Pull request by rdrsadhu**
Concatenation of #58 #59 #60 #61 #62 
Please see the above for details.

They were merged because, a lot of pages(to be migrated next) interconnects to these above pages(in 58-62), and having these across different branches, increased the complexity of task.

I'll continue adding more commits to this branch as I move pages henceforth. Feel free to review at your own pace.

### CODE REVIEW

**Comment by rdrsadhu** [comment]
@quozl @walterbender
mentions just to keep you in sync

**Comment by quozl** [comment]
Thanks!

**Comment by rdrsadhu** [comment]
> Will you be closing the other pull requests?

done. thanks!

**Comment by quozl** [comment]
Thanks.  Please signal when all Activities/Turtle_Art is complete.

**Comment by rdrsadhu** [comment]
thanks,
all ``Activities/Turtle_Art/Tutorials`` is complete.

Rest of the ``Activities/Turtle_Art`` pages mostly are a part of [1]
But [1] have already been migarted and is available at https://help.sugarlabs.org/en/turtleart.html
so I'm not sure if those rest of the pages needs to be added (it mostly depends on the content; in my opinion)

maybe @walterbender or any other turtleart maintainer can help in the decision making process?

---
[1] https://wiki.sugarlabs.org/go/Activities/Turtle_Art

**Comment by quozl** [comment]
@rdrsadhu, would you like to resolve conflicts and squash these commits into one?  I don't like having to add 37 commits at once, some of which are merges, as it will make history unnecessarily complex.

**Comment by rdrsadhu** [comment]
> would you like to resolve conflicts and squash these commits into one?

sure, but wouldn't it make reviewing harder ?

**Comment by quozl** [comment]
How would it make reviewing harder?

**Comment by rdrsadhu** [comment]
Presently each commit migrates one page (except the merges)

I'm not sure if all the pages are required to be added, because some of these contain very little information (like just 1 or 2 sentence) https://github.com/godiard/help-activity/pull/64/commits/3dc055bc4b409894a6721c05c704d245c220fa54 https://github.com/godiard/help-activity/pull/64/commits/ea9b7c9056829a8cc3f3df1f63cdd0d1dd76188b

Squashing these may make it difficult to detect broken links while removing unwanted pages

A better alternative would be review these pages commit-by-commit first, remove unwanted pages(commits), and then use squash-and-merge while merging to master


I might be wrong. Please suggest better alternatives(if any)

**Comment by quozl** [comment]
I see what you mean, thanks.

**Comment by quozl** [comment]
Please rebase.

**Pull request merged**
