### PR TITLE
migrate Activities/Turtle_Art/Tutorials/Numerals and its subpages

### PR DESCRIPTION
**Pull request by rdrsadhu**
This Pull Request migrates documentation from

1. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Numerals/Counting_Rod_Numerals_Program
2. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Numerals/Cuneiform_Wedge_Glyph_Program
3. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Numerals/Kharosthi_Numerals_Program
4. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Numerals/Mayan_Numerals_Program
5. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Numerals

Steps to perform after this Pull Request gets merged:
- [ ] Deprecate wiki-pages 1,2,3,4,5
Note:
* [TurtleArt/Tutorials/Numerals/Counting Rod Numerals Program](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Numerals/Counting_Rod_Numerals_Program&redirect=no) redirects to 1
* [TurtleArt/Tutorials/Numerals/Cuneiform Wedge Glyph Program](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Numerals/Cuneiform_Wedge_Glyph_Program&redirect=no) redirects to 2
* [TurtleArt/Tutorials/Numerals/Kharosthi Numerals Program](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Numerals/Kharosthi_Numerals_Program&redirect=no) redirects to 3
* [TurtleArt/Tutorials/Numerals/Mayan Numerals Program](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Numerals/Mayan_Numerals_Program&redirect=no) redirects to 4
* [TurtleArt/Tutorials/Numerals](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Numerals&redirect=no) redirects to 5

### CODE REVIEW

**Comment by quozl** [comment]
Reviewed.  https://github.com/godiard/help-activity/pull/58 in addition to https://github.com/godiard/help-activity/pull/59 may cause a merge conflict.  How do you want that handled?  Holding off for an answer and resolution of 59.

**Comment by rdrsadhu** [comment]
> Holding off for an answer and resolution of 59

you mean resolution of #58 ?

> How do you want that handled?

Once #58 gets merged; I'll prefer to resolve the conflicts by updating the files
It'll just be 1 file (``source/turtleart_tutorials/tutorial_index.rst``) I guess

**Comment by quozl** [comment]
Thanks, yes.

**Comment by rdrsadhu** [comment]
closing this, duplicated at #64

**Pull request closed without merging**
