### PR TITLE
Migrate Turtle Art Tutorials from wiki

### PR DESCRIPTION
**Pull request by rdrsadhu**
This Pull Request migrates documentation from

1. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Complex_Numbers
2. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Fractions
3. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Galilean_Relativity
4. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Trigonometry

Steps to perform after this Pull Request gets merged:
- [ ] Deprecate wiki-pages 1,2,3,4
Note:
* [TurtleArt/Tutorials/Complex Numbers](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Complex_Numbers&redirect=no) redirects to 1
* [TurtleArt/Tutorials/Fractions](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Fractions&redirect=no) redirects to 2
* [TurtleArt/Tutorials/Galilean Relativity](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Galilean_Relativity&redirect=no) redirects to 3
* [TurtleArt/Tutorials/Trigonometry](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Trigonometry&redirect=no) redirects to 4

### CODE REVIEW

**Comment by rdrsadhu** [comment]
@quozl can you please review this and a few other similar pull requests?

because, for the next set of pages to be moved, they are linked to pages above.
And having these merged, makes the job a bit less complex.

thanks :)

**Comment by quozl** [comment]
I'm not that familiar with the content.  I'm hoping @walterbender will review since he is an activity maintainer for Turtle Art.

If the delay is causing you problem, combine your commits for all the pull requests into a branch and open a new pull request against that branch.  Continue working on that branch for all Turtle Art changes until it is merged.

**Comment by walterbender** [comment]
These are OK...

**Comment by rdrsadhu** [comment]
> If the delay is causing you problems with complexity, combine your commits for all the pull requests into a branch and open a new pull request against that branch. Continue working on that branch for all Turtle Art changes until it is merged.

thank you for the tips :) I've opened #64 and will use the same to move pages of turtle-art tutorials henceforth.



> But I cannot merge.

Permission issues; I believe. 
probable solutions?

**Comment by quozl** [comment]
Oh, I guess because @godiard has not added @walterbender as collaborator.  I hadn't thought of that, sorry.

**Comment by rdrsadhu** [comment]
closing this, duplicated at #64

**Pull request closed without merging**
