### PR TITLE
migrate Activities/Turtle_Art/Tutorials/Counting and its subpages

### PR DESCRIPTION
**Pull request by rdrsadhu**
This Pull Request migrates documentation from

1. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Counting
2. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Counting/TA_Counting_Program
3. https://wiki.sugarlabs.org/go/Activities/Turtle_Art/Tutorials/Elementary_Arithmetic

Steps to perform after this Pull Request gets merged:
- [ ] Deprecate wiki-pages 1,2,3
Note:
* [TurtleArt/Tutorials/Counting](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Counting&redirect=no) redirects to 1
* [TurtleArt/Tutorials/Counting/TA Counting Program](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Counting/TA_Counting_Program&redirect=no) redirects to 2
* [TurtleArt/Tutorials/Elementary Arithmetic](https://wiki.sugarlabs.org/index.php?title=Activities/TurtleArt/Tutorials/Elementary_Arithmetic&redirect=no) redirects to 3

### CODE REVIEW

**Comment by rdrsadhu** [comment]
@divyanshu-rawat @iamonuwa @walterbender
would you like to review some of the pull requests regarding migrating the wiki-pages?

@quozl has been reviewing all of these so far. and since there are a lot of pages to be migrated; I guess he might be needing some help :)

**Comment by quozl** [comment]
Sorry, I'm not dropping the notifications, I'm holding them for when I have time.  Other reviewers are @Pro-panda and @yashagrawal3.  @walterbender would be a good choice, since it is Turtle Art.

**Comment by rdrsadhu** [comment]
> Sorry, I'm not dropping the notifications, I'm holding them for when I have time.

sure, no problem!

**Comment by Pro-Panda** [comment]
Sure, I will start reviewing
Although, I have used only about 60 activities, and will be able to review only them (since its not just migrating, but also improving the docs for a user)

**Comment by walterbender** [comment]
The figures on these pages are from a really old version of Turtle. The blocks interconnect quite differently now. Maybe we need to mark pages that need to have there figures redrawn? These could be good beginner tasks.

**Comment by rdrsadhu** [comment]
> Maybe we need to mark pages that need to have there figures redrawn?

How exactly? I mean the procedure
One possible option is for activity authors/maintainers to go through the documentation pages, after they've been migrated, and create a list of pages to be updated with figures/screenshots.

Beginners can then use the list and get started.

**Comment by walterbender** [comment]
Yes. I don't think there is a practical way to automate this. Should I make the pages in the wiki somehow? Or mark pages in the help activity as they are added?

**Comment by rdrsadhu** [comment]
> mark pages in the help activity as they are added

+1
because
* as authors/maintainers go through the help-activity, they may come across other potential improvements

**Comment by quozl** [comment]
Reviewed.  No issues.  Not sure if consensus is to merge, so holding off.

**Comment by walterbender** [comment]
I think the pages are OK to merge but they could be improved.

**Comment by quozl** [comment]
@walterbender, thanks.  @rdrsadhu, do you plan to improve?

**Comment by rdrsadhu** [comment]
> do you plan to improve?

Honestly, I haven't used the activities extensively and may not be the best person for the job at the moment.

**Comment by quozl** [comment]
Thanks.  While you aren't the best person for the job, the best person is busy with other stuff.  You are therefore one of the best people for the job. :grin:

https://github.com/godiard/help-activity/issues/36 already exists for updating screenshots; there are plenty to do for anyone with time on their hands.

Making a screenshot is straightforward; `virt-manager` part of KVM has a screenshot menu option, Sugar has an `alt-1` screenshot shortcut, and there are tools such as `scrot` for semi-automating, and methods for making a custom desktop shortcut to run a script of your own writing.  I can't be specific, because I don't know what tools you use for running Sugar or activities.

**Comment by rdrsadhu** [comment]
> there are plenty to do for anyone with time on their hands

once someone goes through the help-activity and generates a list of pages to be updated, I guess the process will be easier.

We'll gain a broader overview on the content to be updated. Plus, it is always better to plan things, and then proceed accordingly.

> @rdrsadhu, do you plan to improve?

Not now but maybe I'll update the pages, later in the summer.
Till then, I don't find any reason to hold off this PR. :)

**Comment by rdrsadhu** [comment]
closing this, duplicated at #64

**Pull request closed without merging**
