### PR TITLE
Migrate Documentation from wiki-pages

### PR DESCRIPTION
**Pull request by rdrsadhu**
This Pull Request migrates wiki-pages of Abacus Activity from https://wiki.sugarlabs.org/go/Activities
specifically these 4 pages:
1. https://wiki.sugarlabs.org/go/Activities/Abacus
2. https://wiki.sugarlabs.org/go/Activities/Abacus/Abacos
3. https://wiki.sugarlabs.org/go/Activities/Abacus/Worksheet
4. https://wiki.sugarlabs.org/go/Activities/Abacus/Worksheet/Answersheet

**Description:**
For page:
1. this page was derived to [abacus.rst](https://github.com/sugarlabs/help-activity/blob/master/source/abacus.rst) some time ago, and nothing new has been added since then
* hence it is needless to duplicate the content
2. Spanish Translation of page 1.
* I guess, this page also need not be migrated because, the Help-Activity automatically renders a translated page, according to the user language-preference
3. this page is a lesson plan for learning Abacus. It has been translated to markdown and included in this PR
4. this page contains answers to the lesson plans of page 3. It has also been translated to markdown and included in this PR

Steps to perform after this Pull Request gets merged:
- [ ] Delete wiki-pages 1,2,3,4 and all of its associated extra images/files

### CODE REVIEW

**Comment by quozl** [comment]
Thanks!

**Comment by rdrsadhu** [comment]
Hi @quozl ,
I seem to have missed something

the 'Some lesson plans' link at https://help.sugarlabs.org/en/abacus.html#learning-with-abacus is presently wrong. I assumed the .rst part will automatically be converted to .html (my bad)

The mistake is in commit [Update page links](https://github.com/godiard/help-activity/pull/38/commits/507cbb2059cecaec7336674cc82ea8cedf23fe64)

if those links are changed to *.html, the website would render the page `abacus_worksheet` correctly,
whereas when read from [Github](https://github.com/godiard/help-activity/blob/master/source/abacus.rst), it will be broken

I need some help
Can you tell me how were documents in [html/es/](https://github.com/godiard/help-activity/tree/master/html/es) folder generated?
also what exactly is the use of [helplink.json](https://github.com/godiard/help-activity/blob/master/helplink.json)

An alternative solution to the problem is to store these files in https://github.com/sugarlabs/activity-abacus as in this [PR](https://github.com/sugarlabs/activity-abacus/pull/13)

**Comment by godiard** [comment]
Hi @rdrsadhu,

How to generate files in html/es/: https://github.com/godiard/help-activity/blob/master/howto_translate.rst

helplink.json is used by sugar to show contextual help. When you are using a activity and request help, will check in the helplink.json file for the bundle_id (the same is defined in the activity.info file) and look what is the help html page.

Perhaps this is a good information to put in a Help activity Readme

**Comment by rdrsadhu** [comment]
thanks @godiard,
I've sent in a PR #39 to add some helpful information to the help-activity README

@quozl,
I studied several options to interlink documentation pages of sphinx (such as [:ref:](http://www.sphinx-doc.org/en/stable/markup/inline.html#cross-referencing-arbitrary-locations))
but none of them is ideal for this situation where we want to preserve the readability both in .rst and .html using the same file.
The best option according to me is therefore to use absolute links. I've sent in a PR #40 accordingly

thanks

**Comment by Aruwajiore** [comment]
This Pull Request migrates wiki-pages of Abacus Activity from https://wiki.sugarlabs.org/go/Activities
specifically these 4 pages:

https://wiki.sugarlabs.org/go/Activities/Abacus
https://wiki.sugarlabs.org/go/Activities/Abacus/Abacos
https://wiki.sugarlabs.org/go/Activities/Abacus/Worksheet
https://wiki.sugarlabs.org/go/Activities/Abacus/Worksheet/Answersheet
Description:
For page:

I guess, this page also need not be migrated because, the Help-Activity automatically renders a translated page, according to the user language-preference
this page is a lesson plan for learning Abacus. It has been translated to reStructuredText and included in this PR

this page was derived to abacus.rst some time ago, and nothing new has been added since then
hence it is needless to duplicate the content
Spanish Translation of page 1.

**Comment by quozl** [comment]
@Aruwajiore, you have said nothing except quoted @rdsadhu.  If you have something to say, please say it again.

**Pull request merged**
