### PR TITLE
Update Jukebox documentation

### PR DESCRIPTION
**Pull request by rdrsadhu**
This Pull Request migrates documentation from

1. https://wiki.sugarlabs.org/go/Activities/Jukebox

Most of the updated content was already available at the help-activity via https://github.com/godiard/help-activity/commit/063ff2aa4b417da9ad91fc00eadf5e484c136a91 and https://github.com/godiard/help-activity/commit/195732e0bc3e7a5fda945707f37813fc12666c9f

Added
* content to 'Using' section
* 'Where to report problems' section
* 'Credits' section

Steps to perform after this Pull Request gets merged:
- [ ] Redirect wiki-page 1

### CODE REVIEW

**Comment by quozl** [comment]
We don't have a volume control now.  We also don't have visualisations for audio.  So this content is out of date.  Please make screenshots from the current version of Jukebox and Sugar.

**Comment by godiard** [comment]
Please create screenshots with a max width of 600/800px https://help.sugarlabs.org/how_to_help.html#tutorial-3-adding-an-image

**Comment by rdrsadhu** [comment]
Updated.

**Comment by quozl** [comment]
Thanks.  Reviewed to 06e2e21.

**Pull request merged**
