### PR TITLE
Fix broken Hyperlinks of Abacus

### PR DESCRIPTION
**Pull request by rdrsadhu**
Please follow the discussion at #38

### CODE REVIEW

**Comment by quozl** [comment]
When Help activity is bundled from source, these links will not use the local filesystem.  For an instance of Sugar running without network access, the links will be broken.

**Comment by rdrsadhu** [comment]
what do you suggest then?
for sphinx to interlink the pages correctly, we may have to compromise the same in GitHub
or vice-versa

**Comment by quozl** [comment]
I have no interest in the GitHub rendering of the Help Activity.  So as long as it works in the Help Activity bundle in Sugar desktop, and on the help.sugarlabs.org web site, I'll accept it.  However, if you can make it work on GitHub as well, great!

**Comment by rdrsadhu** [comment]
updated, PTAL

**Pull request merged**
